export default function TrustCenterPage() {
  const controls = [
    ['Confidentiality by design', 'Private business identity, addresses, internal notes, call transcripts, and unapproved financial details are never part of the public listing feed.'],
    ['Seller-controlled disclosure', 'A listing requires documented seller approval and broker review before public publication or partner-network distribution.'],
    ['Permission-aware AI', 'AI access follows the same file and buyer permissions as the user. Blocked content is not used to answer questions.'],
    ['Evidence-backed answers', 'Financial and operating claims can be linked to approved source documents with verification level, confidence, reviewer, and expiration.'],
    ['Broker accountability', 'Agency administrators control advisor roles, listing approvals, commission rules, training, certification, and external publishing.'],
    ['Auditability', 'Sensitive AI actions, disclosures, document access, approvals, exports, and publication events are designed to produce reviewable records.'],
  ]
  return <main style={{ background: '#f4f7fb', minHeight: '100vh' }}><section style={{ background: '#071827', color: '#fff', padding: '76px 24px' }}><div style={{ maxWidth: 1000, margin: '0 auto' }}><div style={{ color: '#76d7ea', textTransform: 'uppercase', letterSpacing: '.18em', fontSize: 12, fontWeight: 900 }}>Marketplace Trust Center</div><h1 style={{ color: '#fff', fontSize: 50, maxWidth: 780, margin: '14px 0' }}>Confidential transactions need visible controls.</h1><p style={{ color: '#cbdbe7', fontSize: 17, lineHeight: 1.65, maxWidth: 760 }}>This page explains platform controls. Each brokerage must publish its own approved legal, licensing, security, accessibility, AI-use, complaint, copyright, and incident-response information.</p></div></section><section style={{ maxWidth: 1000, margin: '0 auto', padding: '54px 24px 80px', display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: 18 }}>{controls.map(([title, body], index) => <article key={title} className="card" style={{ padding: 24, background: '#fff' }}><div style={{ color: '#0e7490', fontWeight: 900, fontSize: 12 }}>CONTROL {String(index + 1).padStart(2, '0')}</div><h2 style={{ fontSize: 20, margin: '10px 0' }}>{title}</h2><p style={{ color: '#52606d', lineHeight: 1.6, margin: 0, fontSize: 13.5 }}>{body}</p></article>)}</section></main>
}
