/**
 * Concord Deal Platform
 * Copyright (c) 2026 Rabin Timsina (EZ Business Advisors LLC). All rights reserved.
 * Proprietary & confidential. No copying, distribution, or modification without
 * prior written permission. See LICENSE for full terms.
 */

import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Sample CIM, BOV & Recast — See Concord\'s Broker-Grade Deliverables | Concord Deal Platform',
  description: 'Preview the actual quality of Concord\'s AI-generated Confidential Information Memorandum, Broker\'s Opinion of Value, and financial recast — before you subscribe. Sample documents from a realistic home-care listing.',
}

/**
 * /samples — public showcase of broker-grade deliverables for prospective
 * agencies (audit fix 09-01: the missing sales tool — agencies could not see
 * a sample CIM/BOV before buying). Static page linking the real generated
 * PDFs (public/samples/*.pdf from scripts/sample-deliverables.mts).
 */
export default function SamplesPage() {
  const docs = [
    {
      key: 'cim',
      icon: '📘',
      name: 'Confidential Information Memorandum',
      short: 'CIM',
      pdf: '/samples/cim.pdf',
      preview: '/samples/cim-preview.png',
      pages: 35,
      desc: 'The full marketing document buyers and lenders read: executive summary, business overview, operations, financial performance with multi-year trend analysis, growth opportunities, and deal structure.',
    },
    {
      key: 'bov',
      icon: '📗',
      name: 'Broker\'s Opinion of Value',
      short: 'BOV',
      pdf: '/samples/bov.pdf',
      preview: '/samples/bov-preview.png',
      pages: 28,
      desc: 'A defensible value range: SDE/EBITDA recast with add-back justification, market comparables by industry multiple band, sensitivity analysis, and pushback section — not a thin one-pager.',
    },
    {
      key: 'recast',
      icon: '📙',
      name: 'Financial Recast',
      short: 'Recast',
      pdf: '/samples/recast.pdf',
      preview: null,
      pages: 9,
      desc: 'The normalized earnings picture: Net Income + itemized add-backs = SDE, with missing categories surfaced for broker review and a hard consistency invariant checked before any document is generated.',
    },
  ]

  return (
    <main style={{ background: '#faf9f4', minHeight: '100vh' }}>
      {/* Hero */}
      <section style={{ background: 'linear-gradient(135deg,#071827 0%,#0f3460 100%)', color: '#fff', padding: '72px 24px 64px', textAlign: 'center' }}>
        <div style={{ maxWidth: 860, margin: '0 auto' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 10, background: 'rgba(201,168,76,0.12)', border: '1px solid rgba(201,168,76,0.35)', borderRadius: 999, padding: '7px 16px', fontSize: 12.5, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase', color: '#f0d98c', marginBottom: 18 }}>
            📄 Sample Deliverables
          </div>
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(32px, 4.4vw, 48px)', margin: '0 0 14px', lineHeight: 1.1, letterSpacing: '-0.02em' }}>
            See the documents <span className="grad-gold">before you buy</span>
          </h1>
          <p style={{ color: 'rgba(255,255,255,0.75)', fontSize: 16, lineHeight: 1.7, maxWidth: 640, margin: '0 auto' }}>
            Every Concord listing ships with a broker-grade CIM, BOV, and recast — generated by AI, validated by the financial engine, and approved by a human broker. These are real samples from a realistic home-care listing (BrightPath Home Care, Charlotte NC metro). Download them and judge the quality yourself.
          </p>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap', marginTop: 28 }}>
            <Link href="/samples/cim.pdf" target="_blank" style={{ background: 'linear-gradient(135deg,#f0d98c,#c9a84c 55%,#b08d35)', color: '#141a2e', border: 'none', borderRadius: 12, padding: '14px 28px', fontWeight: 800, fontSize: 15, textDecoration: 'none', boxShadow: '0 10px 30px rgba(201,168,76,0.35)' }}>
              📘 Download sample CIM
            </Link>
            <Link href="/pricing" style={{ border: '1px solid rgba(255,255,255,0.4)', color: '#fff', borderRadius: 12, padding: '14px 28px', fontWeight: 700, fontSize: 15, textDecoration: 'none' }}>
              See plans →
            </Link>
          </div>
        </div>
      </section>

      {/* Document cards */}
      <section style={{ maxWidth: 1080, margin: '0 auto', padding: '56px 24px 72px' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 20 }}>
          {docs.map((d) => (
            <div key={d.key} style={{ background: '#fff', border: '1px solid #ece8dc', borderRadius: 16, overflow: 'hidden', display: 'flex', flexDirection: 'column', boxShadow: '0 8px 32px rgba(26,26,46,0.08)' }}>
              {d.preview && (
                <div style={{ background: '#102b40', padding: '14px 14px 0', display: 'flex', justifyContent: 'center' }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={d.preview} alt={`${d.short} sample page preview`} style={{ width: '100%', maxHeight: 220, objectFit: 'contain', borderRadius: '8px 8px 0 0' }} />
                </div>
              )}
              {!d.preview && (
                <div style={{ background: 'linear-gradient(135deg,#0f2038,#153e5c)', color: '#c9a84c', padding: '34px 24px', fontSize: 44, textAlign: 'center' }}>{d.icon}</div>
              )}
              <div style={{ padding: '22px 24px', display: 'flex', flexDirection: 'column', gap: 8, flex: 1 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div style={{ fontSize: 17, fontWeight: 800, color: '#1a1a2e', fontFamily: 'Georgia, serif' }}>{d.name}</div>
                  <span style={{ fontSize: 11, fontWeight: 800, color: '#8a6d1a', background: '#fdf6e3', padding: '4px 10px', borderRadius: 99 }}>{d.pages} pages</span>
                </div>
                <p style={{ fontSize: 13.5, color: '#666', lineHeight: 1.6, margin: 0, flex: 1 }}>{d.desc}</p>
                <Link href={d.pdf} target="_blank" style={{ marginTop: 12, display: 'inline-block', textAlign: 'center', padding: '11px 18px', borderRadius: 9, background: '#1a1a2e', color: '#c9a84c', textDecoration: 'none', fontWeight: 800, fontSize: 13.5 }}>
                  ⬇ Download {d.short} (PDF)
                </Link>
              </div>
            </div>
          ))}
        </div>

        {/* Why it matters */}
        <div style={{ marginTop: 40, background: '#fff', border: '1px solid #ece8dc', borderRadius: 16, padding: '30px 32px' }}>
          <div style={{ fontSize: 12, letterSpacing: '0.16em', textTransform: 'uppercase', color: '#8a6d1a', fontWeight: 800, marginBottom: 14 }}>Why this matters</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 18 }}>
            {[
              ['🧮', 'Validated math', 'SDE = Net Income + itemized add-backs, checked by a hard invariant inside the engine — the double-count bug class is locked by regression tests.'],
              ['🤖', 'AI-powered, human-approved', 'AI drafts from your documents and interview; a licensed broker reviews and approves before anything ships.'],
              ['⚖️', 'Defensible range', 'BOV uses industry multiple bands (e.g., home care 4–5× EBITDA), comparables, sensitivity, and pushback — built to survive buyer and lender scrutiny.'],
              ['⚡', 'Minutes, not weeks', 'Documents that take an analyst a week generate in minutes from documents the seller already has.'],
            ].map(([icon, t, b]) => (
              <div key={t as string} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <span style={{ fontSize: 24, flexShrink: 0 }}>{icon}</span>
                <div>
                  <div style={{ fontSize: 14.5, fontWeight: 800, color: '#1a1a2e' }}>{t}</div>
                  <div style={{ fontSize: 12.5, color: '#777', lineHeight: 1.55, marginTop: 4 }}>{b}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div style={{ textAlign: 'center', marginTop: 40 }}>
          <Link href="/platform" style={{ display: 'inline-block', background: '#0e7490', color: '#fff', padding: '14px 30px', borderRadius: 12, textDecoration: 'none', fontWeight: 800, fontSize: 15 }}>
            Launch your own brokerage on Concord →
          </Link>
        </div>
      </section>
    </main>
  )
}
