/**
 * Concord Deal Platform
 * Copyright (c) 2026 Rabin Timsina (EZ Business Advisors LLC). All rights reserved.
 * Proprietary & confidential. No copying, distribution, or modification without
 * prior written permission. See LICENSE for full terms.
 */

import { NextRequest, NextResponse } from 'next/server'
import crypto from 'crypto'
import { createServerClient } from '@/lib/supabase/server'
import { rateLimitAsync } from '@/lib/rateLimit'
import { chatWithDeepSeek, isDeepSeekConfigured } from '@/lib/deepseek/client'

export const runtime = 'nodejs'

const clientIp = (req: Request) =>
  req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ||
  req.headers.get('x-real-ip') ||
  'unknown'

// =============================================================================
// POST /api/chat-widget/message — website chat widget → agent pipeline
// -----------------------------------------------------------------------------
// Stores a visitor message in call_sessions/call_transcripts
// (purpose='chat_widget'). The local watcher picks it up, the agent replies,
// and the widget polls /api/chat-widget/poll for the assistant message.
// Works for public website AND CRM dashboard (mode field).
// =============================================================================

export async function POST(req: NextRequest) {
  // Anti-abuse: public-ish endpoint — rate limited per IP.
  if (!(await rateLimitAsync(clientIp(req), { limit: 10, windowMs: 60 * 1000 }))) {
    return NextResponse.json({ ok: false, error: 'Too many requests. Try again later.' }, { status: 429 })
  }
  const db = createServerClient()
  if (!db) return NextResponse.json({ ok: false, error: 'Service unavailable' }, { status: 503 })

  const agencyId = process.env.VOICE_AGENT_AGENCY_ID || ''
  if (!agencyId) return NextResponse.json({ ok: false, error: 'Chat agent is not configured' }, { status: 503 })

  let body: any = {}
  try { body = await req.json() } catch { /* fall through */ }
  const message = String(body?.message || '').trim().slice(0, 1000)
  if (!message) return NextResponse.json({ ok: false, error: 'Message is required' }, { status: 400 })

  const mode = body?.mode === 'crm' ? 'crm' : 'public'
  let sessionId = String(body?.sessionId || '').trim().slice(0, 64)
  if (!sessionId) sessionId = `web_${crypto.randomUUID()}`

  // Reuse an open thread for this visitor, else start one.
  const { data: existing } = await db
    .from('call_sessions')
    .select('id')
    .eq('agency_id', agencyId)
    .eq('provider', 'web')
    .eq('purpose', 'chat_widget')
    .eq('caller_number', sessionId)
    .eq('status', 'in_progress')
    .limit(1)
    .maybeSingle()

  let dbSessionId: string
  if (existing?.id) {
    dbSessionId = existing.id
  } else {
    const { data: created, error } = await db
      .from('call_sessions')
      .insert({
        agency_id: agencyId,
        provider: 'web',
        purpose: 'chat_widget',
        direction: 'inbound',
        status: 'in_progress',
        caller_number: sessionId,
        metadata: { last_processed_at: null, mode },
        started_at: new Date().toISOString(),
      })
      .select('id')
      .single()
    if (error || !created?.id) return NextResponse.json({ ok: false, error: 'Failed to open chat session' }, { status: 500 })
    dbSessionId = created.id
  }

  const { error } = await db.from('call_transcripts').insert({
    agency_id: agencyId,
    call_session_id: dbSessionId,
    sequence: Date.now() % 100000,
    speaker: 'caller',
    content: message,
  })
  if (error) return NextResponse.json({ ok: false, error: 'Failed to store message' }, { status: 500 })

  // ── Server-side AI reply (no local watcher needed) ──────────────────────
  // Previously the reply was generated by a LOCAL watcher script polling the
  // OpenClaw gateway loopback — which only works on the owner's desktop. On
  // Vercel/the VPS that watcher never runs, so the bot silently never replied.
  // Now the assistant answers here, in-process, via DeepSeek, and the reply is
  // stored in the same thread so the widget's existing /api/chat-widget/poll
  // picks it up unchanged.
  let aiError: string | null = null
  try {
    if (isDeepSeekConfigured()) {
      const isCrm = mode === 'crm'
      const system = isCrm
        ? 'You are the AI assistant inside a business-brokerage CRM (EZ Business Advisors). Help the broker use the platform: listings, deal pipeline, lead management, NDA/listing agreements, documents, AI agents, calendar, communications, training. Answer briefly and concretely; point to the right tool/page when relevant. Never invent features that do not exist.'
        : 'You are the friendly AI assistant for a business brokerage website. Help visitors buy a business, sell their business, join the broker network, or contact a broker. Answer briefly and warmly. Do not disclose confidential business financials; tell buyers to request details through the site.'
      // Direct DeepSeek call (bypasses client lib) — minimal payload that is
      // proven to return content; no response_format/thinking params that could
      // trigger empty-content responses in the serverless runtime.
      const dsRes = await fetch('https://api.deepseek.com/chat/completions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.DEEPSEEK_API_KEY}` },
        body: JSON.stringify({
          model: 'deepseek-chat',
          messages: [
            { role: 'system', content: system },
            { role: 'user', content: message },
          ],
          max_tokens: 400,
          stream: false,
        }),
        signal: AbortSignal.timeout(40_000),
      })
      if (!dsRes.ok) {
        aiError = `DeepSeek HTTP ${dsRes.status}`
      } else {
        const payload = await dsRes.json().catch(() => null) as { choices?: Array<{ message?: { content?: string | null } }> } | null
        const reply = (payload?.choices?.[0]?.message?.content || '').trim().slice(0, 1500)
        if (reply) {
          const { error: insErr } = await db.from('call_transcripts').insert({
            agency_id: agencyId,
            call_session_id: dbSessionId,
            sequence: (Date.now() + 1) % 100000,
            speaker: 'assistant',
            content: reply,
          })
          if (insErr) aiError = 'insert failed: ' + insErr.message
        } else {
          aiError = 'DeepSeek returned empty content'
        }
      }
    }
  } catch (e) {
    aiError = e instanceof Error ? e.message : String(e)
    console.error('[chat-widget] AI reply failed:', aiError)
  }

  return NextResponse.json({ ok: true, sessionId, dbSessionId })
}
