-- Concord Deal Platform
-- Copyright (c) 2026 Rabin Timsina (EZ Business Advisors LLC). All rights reserved.
-- Proprietary & confidential. No copying, distribution, or modification without
-- prior written permission. See LICENSE for full terms.

-- =============================================================================
-- Concord Deal Platform — US locations reference table
-- Run in the Supabase SQL Editor (idempotent — safe to re-run any time).
-- -----------------------------------------------------------------------------
-- Powers the location search autocomplete (typing "H" -> "Harrisburg, PA").
-- Contains US cities, counties and states. Populated via:
--   node scripts/seed-locations.mjs
-- =============================================================================

create table if not exists public.locations (
  id         bigint generated by default as identity primary key,
  name       text not null,           -- e.g. 'Harrisburg' | 'Harris County' | 'Pennsylvania'
  state_code text not null,           -- e.g. 'PA'
  state_name text,                    -- e.g. 'Pennsylvania'
  place_type text not null default 'city'
             check (place_type in ('city', 'county', 'state', 'zip')),
  display    text not null,           -- e.g. 'Harrisburg, PA' | 'Pennsylvania'
  population int,
  lat        double precision,
  lng        double precision,
  created_at timestamptz not null default now()
);

-- Fast prefix lookups on the autocomplete ("har%").
create index if not exists locations_name_lower_idx
  on public.locations (lower(name));

-- Case-insensitive uniqueness guard (prevents 'harrisburg' + 'Harrisburg' dupes).
create unique index if not exists locations_name_state_type_uidx
  on public.locations (lower(name), state_code, place_type);

-- Plain-column unique index: PostgREST cannot target expression indexes in
-- ON CONFLICT ("column lower does not exist"), so the seed script upserts on
-- these columns. Seed data is consistently title-cased, so this index is
-- fully redundant with the lower() guard above for rows written by the seed.
create unique index if not exists locations_name_state_type_plain_uidx
  on public.locations (name, state_code, place_type);

-- Public reference data: allow anon read for the autocomplete endpoint.
alter table public.locations enable row level security;
drop policy if exists locations_select_all on public.locations;
create policy locations_select_all on public.locations
  for select using (true);
